/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AttachmentResponse {
  id?: string;
  entityType?: string;
  entityId?: string;
  filename?: string;
  contentType?: string;
  sizeBytes?: number;
  uploadedBy?: string;
  createdAt?: string;
}
