/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { RefItemResponse } from './ref-item-response';

export interface PagedModelRefItemResponse {
  content?: Array<RefItemResponse>;
  page?: PageMetadata;
}
